// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealTimeMVCapp.Context;

namespace RealTimeMVCapp.Migrations
{
    [DbContext(typeof(RealTimeContext))]
    partial class RealTimeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RealTimeMVCapp.Data.Entities.Material", b =>
                {
                    b.Property<int>("materialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("materialYFlag")
                        .HasColumnType("int");

                    b.HasKey("materialId");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("RealTimeMVCapp.Data.Entities.MaterialItems", b =>
                {
                    b.Property<int>("materialItemsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("materialDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("materialId")
                        .HasColumnType("int");

                    b.HasKey("materialItemsId");

                    b.HasIndex("materialId");

                    b.ToTable("MaterialItems");
                });

            modelBuilder.Entity("RealTimeMVCapp.Data.Entities.MaterialItems", b =>
                {
                    b.HasOne("RealTimeMVCapp.Data.Entities.Material", "material")
                        .WithMany("materialItems")
                        .HasForeignKey("materialId");
                });
#pragma warning restore 612, 618
        }
    }
}
